[package]
name = "quamatic/flash-list-vide"
description = "Port of FlashList for Vide"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.3.1"
